vpc:
  pkl_vrf: management
  domain: 100
  port_channel:
    id: 1
    members:
      - Ethernet1/2
      - Ethernet1/3
trunks:
  - port_channel_id: 11
    members:
      - Ethernet1/5
hsrp:
  - interface: vlan100
    group: 100
    vip: 172.16.100.1
  - interface: vlan101
    group: 101
    vip: 172.16.101.1
  - interface: vlan102
    group: 102
    vip: 172.16.102.1
  - interface: vlan103
    group: 103
    vip: 172.16.103.1

ospf:
  process_id: 1
  networks:
    - interface: Ethernet1/1
      area: 0
    - interface: Ethernet1/4
      area: 0
    - interface: vlan100
      area: 0
    - interface: vlan101
      area: 0
    - interface: vlan102
      area: 0
    - interface: vlan103
      area: 0
    - interface: loopback0
      area: 0