---

- name: Configure portchannel
  with_items: "{{trunks}}"
  nxos_portchannel:
    group: "{{item.port_channel_id}}"
    members: "{{item.members}}"
    mode: 'active'
    force: true
    mode: on
    state: present


- name: Configure portchannels as trunk
  with_items: "{{trunks}}"
  nxos_switchport:
    interface: "po{{item.port_channel_id}}"
    mode: trunk

- name: Add portchannel to vpc
  with_items: "{{trunks}}"
  nxos_vpc_interface:
    portchannel: "{{item.port_channel_id}}"
    vpc: "{{item.port_channel_id}}"
    