##############################################################
# Learning Series: Network Programmability Basics
# Module: NetDevOps
# Lesson: Ansible Part 3: Your Network as Code
# Author: Hank Preston <hapresto@cisco.com>
#
# Illustrate the following concepts:
# -
##############################################################
---
- name: "Generate NETCONF Loopback config"
  tags: [api, netconf, layer3]
  with_items: "{{l3_interfaces}}"
  template:
    src: "files/ietf_interface_template.j2"
    dest: "./configs/loopback-{{inventory_hostname}}-{{item.interface_type}}{{item.interface_id}}.xml"
  when: item.interface_type == "Loopback"
- name: Configure Loopback with NETCONF
  tags: [api, netconf, layer3]
  with_items: "{{l3_interfaces}}"
  netconf_config:
    host: "{{inventory_hostname}}"
    hostkey_verify: false
    username: admin
    password: admin
    src: "./configs/loopback-{{inventory_hostname}}-{{item.interface_type}}{{item.interface_id}}.xml"
  when: item.interface_type == "Loopback"
