---
- name: Enable Features
  tags: [api, nxapi, layer3]
  with_items:
    - interface-vlan
  nxos_feature:
    provider:
      host: "{{inventory_hostname}}"
      #transport: nxapi
      #https: yes
      timeout: 15
    feature: "{{ item }}"
    state: enabled

- name: Configure Layer 3 Interfaces
  tags: [api, nxapi, layer3]
  with_items: "{{ l3_interfaces }}"
  nxos_interface:
    provider:
      host: "{{inventory_hostname}}"
      #transport: nxapi
      timeout: 15
    interface: "{{ item.interface_type }}{{ item.interface_id }}"
   # mode: layer3
    description: "{{ item.description }}"
    admin_state: up
  when: item.interface_type != "Ethernet"

- name: Configure Layer 3 Interfaces
  tags: [api, nxapi, layer3]
  with_items: "{{ l3_interfaces }}"
  nxos_interface:
    provider:
      host: "{{inventory_hostname}}"
      #transport: nxapi
      timeout: 15
    interface: "{{ item.interface_type }}{{ item.interface_id }}"
    mode: layer3
    description: "{{ item.description }}"
    admin_state: up
  when: item.interface_type == "Ethernet"


- name: Configure IPv4 Address on Interface
  tags: [api, nxapi, layer3]
  with_items: "{{ l3_interfaces }}"
  nxos_ip_interface:
    provider:
      host: "{{inventory_hostname}}"
      #transport: nxapi
      timeout: 15
    interface: "{{ item.interface_type }}{{ item.interface_id }}"
    version: v4
    addr: "{{ item.ip_address }}"
    mask: "{{ item.prefix }}"
